Shimmer loading effect
flet-dev/flet-contrib pull request #8
Opened 2024-01-01 23:50 UTC by lekshmanmj

https://github.com/flet-dev/flet-contrib/assets/35882740/80754b40-a820-4a73-8595-30c73eaac79c

2024-01-01 23:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/flet-dev/flet-contrib?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/flet-dev/flet-contrib?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/flet-dev/flet-contrib?pullRequest=8) it.</sub>

2024-01-02 11:07 UTC, ndonkoHenri commented
Linked issue: https://github.com/flet-dev/flet/issues/521

2024-01-07 17:16 UTC, ndonkoHenri requested changes
I suggest we keep an implicit parameter-setting throughout the code. So instead of: 
```py
gradient = ft.LinearGradient(colors = [self.__color2, self.__color1, self.__color2])
gradient.stops = [0+i-gap,i,gap+i,]
gradient.begin = ft.alignment.top_left
gradient.end = ft.alignment.bottom_right
```
you could instead do:
```py
gradient = ft.LinearGradient(colors=[self.__color2, self.__color1, self.__color2], stops=[0+i-gap,i,gap+i,], begin=ft.alignment.top_left, end=ft.alignment.bottom_right)
```

Several sections of your code should be modified to this style...
Also, can you [black](https://black.readthedocs.io/en/stable/integrations/editors.html)-format the code?

2024-01-17 11:10 UTC, lekshmanmj commented
> I suggest we keep an implicit parameter-setting throughout the code. So instead of:
> 
> ```python
> gradient = ft.LinearGradient(colors = [self.__color2, self.__color1, self.__color2])
> gradient.stops = [0+i-gap,i,gap+i,]
> gradient.begin = ft.alignment.top_left
> gradient.end = ft.alignment.bottom_right
> ```
> 
> you could instead do:
> 
> ```python
> gradient = ft.LinearGradient(colors=[self.__color2, self.__color1, self.__color2], stops=[0+i-gap,i,gap+i,], begin=ft.alignment.top_left, end=ft.alignment.bottom_right)
> ```
> 
> Several sections of your code should be modified to this style... Also, can you [black](https://black.readthedocs.io/en/stable/integrations/editors.html)-format the code?

okay

2024-01-22 12:46 UTC, closed without merging